apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws-ecr-credential.secret" . }}
  namespace: {{ include "aws-ecr-credential.namespace" . }}
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
