apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ecr-credential.serviceAccount" . }}
  namespace: {{ include "aws-ecr-credential.namespace" . }}
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-ecr-credential.serviceAccount" . }}
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ecr-credential.serviceAccount" . }}
    namespace: {{ include "aws-ecr-credential.namespace" . }}
